import { db } from "../../db";
import { conversations, messages } from "@shared/schema";
import { eq, desc } from "drizzle-orm";

export interface IChatStorage {
  getConversation(id: string): Promise<typeof conversations.$inferSelect | undefined>;
  getAllConversations(businessId: string): Promise<(typeof conversations.$inferSelect)[]>;
  createConversation(businessId: string, channel: string, contactName?: string): Promise<typeof conversations.$inferSelect>;
  deleteConversation(id: string): Promise<void>;
  getMessagesByConversation(conversationId: string): Promise<(typeof messages.$inferSelect)[]>;
  createMessage(conversationId: string, role: string, content: string, wasAutoGenerated?: boolean): Promise<typeof messages.$inferSelect>;
}

export const chatStorage: IChatStorage = {
  async getConversation(id: string) {
    const [conversation] = await db.select().from(conversations).where(eq(conversations.id, id));
    return conversation;
  },

  async getAllConversations(businessId: string) {
    return db.select().from(conversations).where(eq(conversations.businessId, businessId)).orderBy(desc(conversations.createdAt));
  },

  async createConversation(businessId: string, channel: string, contactName?: string) {
    const [conversation] = await db.insert(conversations).values({ 
      businessId, 
      channel,
      contactName,
      status: "active"
    }).returning();
    return conversation;
  },

  async deleteConversation(id: string) {
    await db.delete(messages).where(eq(messages.conversationId, id));
    await db.delete(conversations).where(eq(conversations.id, id));
  },

  async getMessagesByConversation(conversationId: string) {
    return db.select().from(messages).where(eq(messages.conversationId, conversationId)).orderBy(messages.createdAt);
  },

  async createMessage(conversationId: string, role: string, content: string, wasAutoGenerated: boolean = false) {
    const [message] = await db.insert(messages).values({ 
      conversationId, 
      role, 
      content,
      wasAutoGenerated
    }).returning();
    return message;
  },
};
