import React, { useState, useRef, useEffect } from "react";
import {
  StyleSheet,
  View,
  ScrollView,
  TextInput,
  Pressable,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useRoute, RouteProp } from "@react-navigation/native";
import { Feather } from "@expo/vector-icons";
import Animated, { FadeIn, FadeInDown } from "react-native-reanimated";
import * as Haptics from "expo-haptics";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/query-client";
import { AnimatedBackground } from "@/components/AnimatedBackground";
import { GlassCard } from "@/components/GlassCard";
import { ThemedText } from "@/components/ThemedText";
import { Colors, Spacing, BorderRadius } from "@/constants/theme";
import { RootStackParamList } from "@/navigation/RootStackNavigator";
import { Message as ApiMessage, Conversation as ApiConversation } from "@shared/schema";

type RouteProps = RouteProp<RootStackParamList, "ConversationDetail">;

interface Message extends ApiMessage {
  isAI?: boolean;
  isPending?: boolean;
  time: string;
}

export default function ConversationDetailScreen() {
  const insets = useSafeAreaInsets();
  const route = useRoute<RouteProps>();
  const { conversationId } = route.params;
  const theme = Colors.dark;
  const scrollViewRef = useRef<ScrollView>(null);
  const [inputText, setInputText] = useState("");
  const queryClient = useQueryClient();

  const { data: conversationData, isLoading: isLoadingConv } = useQuery<ApiConversation & { messages: ApiMessage[] }>({
    queryKey: [`/api/conversations/${conversationId}`],
  });

  const sendMessageMutation = useMutation({
    mutationFn: async (content: string) => {
      return apiRequest("POST", `/api/conversations/${conversationId}/messages`, {
        content,
        role: "user",
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/conversations/${conversationId}`] });
      setInputText("");
    },
  });

  const generateAIResponseMutation = useMutation({
    mutationFn: async () => {
      return apiRequest("POST", "/api/ai/generate-response", {
        conversationId,
        pilotMode: "suggestive",
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/conversations/${conversationId}`] });
    },
  });

  const approveResponseMutation = useMutation({
    mutationFn: async (content: string) => {
      return apiRequest("POST", "/api/ai/approve-response", {
        conversationId,
        content,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/conversations/${conversationId}`] });
    },
  });

  const handleSend = () => {
    if (inputText.trim()) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      sendMessageMutation.mutate(inputText.trim());
    }
  };

  const handleApprove = (content: string) => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    approveResponseMutation.mutate(content);
  };

  const handleGenerateAI = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    generateAIResponseMutation.mutate();
  };

  const formatTime = (date: string | Date) => {
    return new Date(date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const messages = conversationData?.messages.map(m => ({
    ...m,
    time: formatTime(m.createdAt),
    isAI: m.role === 'agent',
    isPending: m.role === 'agent' && !m.wasApproved && m.wasAutoGenerated
  })) || [];

  if (isLoadingConv) {
    return (
      <View style={[styles.container, styles.center]}>
        <ActivityIndicator size="large" color={theme.primary} />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <AnimatedBackground />
      <KeyboardAvoidingView
        style={styles.keyboardView}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        keyboardVerticalOffset={Platform.OS === "ios" ? 90 : 0}
      >
        <ScrollView
          ref={scrollViewRef}
          style={styles.scrollView}
          contentContainerStyle={[
            styles.messagesContainer,
            { paddingBottom: Spacing.xl },
          ]}
          showsVerticalScrollIndicator={false}
          onContentSizeChange={() => scrollViewRef.current?.scrollToEnd({ animated: true })}
        >
          <View style={styles.conversationHeader}>
            <View style={styles.contactInfo}>
              <View style={[styles.avatar, { backgroundColor: `${theme.primary}20` }]}>
                <Feather name="user" size={24} color={theme.primary} />
              </View>
              <View style={styles.contactDetails}>
                <ThemedText type="h4">{conversationData?.contactName || "Contact"}</ThemedText>
                <View style={styles.channelBadge}>
                  <Feather name="message-square" size={12} color={theme.textSecondary} />
                  <ThemedText type="caption" style={{ color: theme.textSecondary, marginLeft: 4 }}>
                    {conversationData?.channel}
                  </ThemedText>
                </View>
              </View>
            </View>
          </View>

          {messages.map((msg, index) => (
            <Animated.View
              key={msg.id}
              entering={FadeInDown.delay(index * 50)}
              style={[
                styles.messageRow,
                msg.role === "agent" || msg.role === "assistant" ? styles.messageRowAgent : styles.messageRowUser,
              ]}
            >
              {(msg.role === "agent" || msg.role === "assistant") ? (
                <View style={styles.agentMessage}>
                  <View style={styles.messageHeader}>
                    {msg.wasAutoGenerated ? (
                      <View style={styles.aiBadge}>
                        <Feather name="cpu" size={10} color={theme.primary} />
                        <ThemedText type="label" style={{ color: theme.primary, marginLeft: 4 }}>
                          AI {msg.isPending ? "DRAFT" : "SENT"}
                        </ThemedText>
                      </View>
                    ) : null}
                    <ThemedText type="caption" style={{ color: theme.textTertiary }}>
                      {msg.time}
                    </ThemedText>
                  </View>
                  <GlassCard style={[styles.messageBubble, msg.isPending ? styles.pendingBubble : {}]}>
                    <ThemedText type="body">{msg.content}</ThemedText>
                  </GlassCard>
                  {msg.isPending ? (
                    <View style={styles.pendingActions}>
                      <Pressable onPress={() => handleApprove(msg.content)} style={styles.approveButton}>
                        <Feather name="check" size={18} color={theme.success} />
                        <ThemedText type="small" style={{ color: theme.success, marginLeft: 4 }}>
                          Approve
                        </ThemedText>
                      </Pressable>
                      <Pressable style={styles.rejectButton}>
                        <Feather name="edit-2" size={16} color={theme.textSecondary} />
                        <ThemedText type="small" style={{ color: theme.textSecondary, marginLeft: 4 }}>
                          Edit
                        </ThemedText>
                      </Pressable>
                    </View>
                  ) : null}
                </View>
              ) : (
                <View style={styles.userMessage}>
                  <View style={styles.messageHeader}>
                    <ThemedText type="caption" style={{ color: theme.textTertiary }}>
                      {msg.time}
                    </ThemedText>
                  </View>
                  <View style={[styles.messageBubble, styles.userBubble]}>
                    <ThemedText type="body">{msg.content}</ThemedText>
                  </View>
                </View>
              )}
            </Animated.View>
          ))}
        </ScrollView>

        <View style={[styles.inputContainer, { paddingBottom: insets.bottom + Spacing.sm }]}>
          <View style={styles.aiControls}>
             <Pressable onPress={handleGenerateAI} style={styles.aiButton}>
               <Feather name="zap" size={16} color={theme.primary} />
               <ThemedText type="small" style={{ color: theme.primary, marginLeft: 6 }}>Generate AI Draft</ThemedText>
             </Pressable>
          </View>
          <GlassCard noPadding style={styles.inputWrapper}>
            <View style={styles.inputRow}>
              <TextInput
                style={styles.input}
                placeholder="Type a message..."
                placeholderTextColor={theme.textTertiary}
                value={inputText}
                onChangeText={setInputText}
                multiline
              />
              <Pressable
                onPress={handleSend}
                disabled={sendMessageMutation.isPending}
                style={[styles.sendButton, { backgroundColor: inputText.trim() ? theme.primary : "rgba(255, 255, 255, 0.1)" }]}
              >
                {sendMessageMutation.isPending ? (
                  <ActivityIndicator size="small" color={theme.text} />
                ) : (
                  <Feather name="send" size={18} color={inputText.trim() ? theme.text : theme.textTertiary} />
                )}
              </Pressable>
            </View>
          </GlassCard>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  center: {
    justifyContent: "center",
    alignItems: "center",
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  messagesContainer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
  },
  conversationHeader: {
    marginBottom: Spacing.xl,
    alignItems: "center",
  },
  contactInfo: {
    alignItems: "center",
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.sm,
  },
  contactDetails: {
    alignItems: "center",
  },
  channelBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  messageRow: {
    marginBottom: Spacing.lg,
  },
  messageRowAgent: {
    alignItems: "flex-start",
  },
  messageRowUser: {
    alignItems: "flex-end",
  },
  agentMessage: {
    maxWidth: "85%",
  },
  userMessage: {
    maxWidth: "85%",
    alignItems: "flex-end",
  },
  messageHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    gap: Spacing.sm,
  },
  aiBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${Colors.dark.primary}20`,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
  },
  messageBubble: {
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
  },
  userBubble: {
    backgroundColor: Colors.dark.primary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
  },
  pendingBubble: {
    borderWidth: 1,
    borderColor: Colors.dark.primary,
    borderStyle: "dashed",
  },
  pendingActions: {
    flexDirection: "row",
    marginTop: Spacing.sm,
    gap: Spacing.sm,
  },
  approveButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${Colors.dark.success}15`,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: `${Colors.dark.success}30`,
  },
  rejectButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  inputContainer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    backgroundColor: "rgba(16, 22, 34, 0.9)",
    borderTopWidth: 1,
    borderTopColor: Colors.dark.glassBorder,
  },
  aiControls: {
    marginBottom: Spacing.sm,
    flexDirection: "row",
    justifyContent: "center",
  },
  aiButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${Colors.dark.primary}10`,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderColor: `${Colors.dark.primary}30`,
  },
  inputWrapper: {
    borderRadius: BorderRadius.xl,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    padding: Spacing.sm,
  },
  input: {
    flex: 1,
    color: Colors.dark.text,
    fontSize: 16,
    maxHeight: 100,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
});
