import React, { useState, useRef, useEffect } from "react";
import {
  StyleSheet,
  View,
  ScrollView,
  TextInput,
  Pressable,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
  Alert,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useRoute, RouteProp, useNavigation } from "@react-navigation/native";
import { Feather } from "@expo/vector-icons";
import Animated, { FadeIn, FadeInDown } from "react-native-reanimated";
import * as Haptics from "expo-haptics";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AnimatedBackground } from "@/components/AnimatedBackground";
import { GlassCard } from "@/components/GlassCard";
import { ThemedText } from "@/components/ThemedText";
import { Colors, Spacing, BorderRadius } from "@/constants/theme";
import { RootStackParamList } from "@/navigation/RootStackNavigator";
import { apiRequest } from "@/lib/query-client";

type RouteProps = RouteProp<RootStackParamList, "ConversationDetail">;

interface ApiMessage {
  id: string;
  conversationId: string;
  role: "user" | "agent" | "system";
  content: string;
  audioUrl: string | null;
  wasAutoGenerated: boolean;
  wasApproved: boolean | null;
  createdAt: string;
}

interface ApiConversation {
  id: string;
  businessId: string;
  agentId: string | null;
  channel: string;
  contactName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  status: string;
  sentiment: string | null;
  summary: string | null;
  createdAt: string;
  updatedAt: string;
  messages: ApiMessage[];
}

function formatTime(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

const getChannelIcon = (channel: string): keyof typeof Feather.glyphMap => {
  switch (channel) {
    case "phone":
      return "phone";
    case "sms":
      return "message-circle";
    case "chat":
    case "webchat":
      return "message-square";
    case "instagram":
      return "instagram";
    case "email":
      return "mail";
    case "whatsapp":
      return "message-circle";
    default:
      return "message-square";
  }
};

export default function ConversationDetailScreen() {
  const insets = useSafeAreaInsets();
  const route = useRoute<RouteProps>();
  const navigation = useNavigation();
  const theme = Colors.dark;
  const scrollViewRef = useRef<ScrollView>(null);
  const queryClient = useQueryClient();
  const [message, setMessage] = useState("");
  const [suggestedResponse, setSuggestedResponse] = useState<string | null>(null);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);

  const { conversationId } = route.params;

  const { data: conversation, isLoading, refetch } = useQuery<ApiConversation>({
    queryKey: ["/api/conversations", conversationId],
  });

  const sendMessageMutation = useMutation({
    mutationFn: async (content: string) => {
      const res = await apiRequest("POST", `/api/conversations/${conversationId}/messages`, {
        content,
        role: "user",
      });
      return res.json();
    },
    onSuccess: () => {
      refetch();
      generateAIResponse();
    },
  });

  const generateAIResponse = async () => {
    setIsGeneratingAI(true);
    try {
      const res = await apiRequest("POST", "/api/ai/generate-response", {
        conversationId,
        pilotMode: "suggestive",
      });
      const data = await res.json();
      if (data.suggestedResponse) {
        setSuggestedResponse(data.suggestedResponse);
      } else if (data.message) {
        refetch();
      }
    } catch (error) {
      console.error("Error generating AI response:", error);
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const approveResponseMutation = useMutation({
    mutationFn: async (content: string) => {
      const res = await apiRequest("POST", "/api/ai/approve-response", {
        conversationId,
        content,
      });
      return res.json();
    },
    onSuccess: () => {
      setSuggestedResponse(null);
      refetch();
    },
  });

  const updateStatusMutation = useMutation({
    mutationFn: async (status: string) => {
      const res = await apiRequest("PATCH", `/api/conversations/${conversationId}`, {
        status,
      });
      return res.json();
    },
    onSuccess: () => {
      refetch();
      queryClient.invalidateQueries({ queryKey: ["/api/businesses"] });
    },
  });

  const handleSend = () => {
    if (message.trim()) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      sendMessageMutation.mutate(message.trim());
      setMessage("");
    }
  };

  const handleApprove = () => {
    if (suggestedResponse) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      approveResponseMutation.mutate(suggestedResponse);
    }
  };

  const handleEdit = () => {
    if (suggestedResponse) {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      setMessage(suggestedResponse);
      setSuggestedResponse(null);
    }
  };

  const handleStatusAction = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    Alert.alert(
      "Update Status",
      "Change the conversation status",
      [
        { 
          text: "Mark Resolved", 
          onPress: () => updateStatusMutation.mutate("resolved") 
        },
        { 
          text: "Transfer to Human", 
          onPress: () => updateStatusMutation.mutate("transferred") 
        },
        { 
          text: "Mark Active", 
          onPress: () => updateStatusMutation.mutate("active") 
        },
        { text: "Cancel", style: "cancel" },
      ]
    );
  };

  useEffect(() => {
    if (conversation?.messages?.length) {
      setTimeout(() => scrollViewRef.current?.scrollToEnd({ animated: true }), 100);
    }
  }, [conversation?.messages?.length]);

  React.useLayoutEffect(() => {
    navigation.setOptions({
      headerRight: () => (
        <Pressable onPress={handleStatusAction} style={{ marginRight: Spacing.md }}>
          <Feather name="more-vertical" size={22} color={theme.text} />
        </Pressable>
      ),
    });
  }, [navigation]);

  if (isLoading) {
    return (
      <View style={[styles.container, styles.loadingContainer]}>
        <AnimatedBackground />
        <ActivityIndicator size="large" color={theme.primary} />
        <ThemedText type="small" style={{ color: theme.textSecondary, marginTop: Spacing.md }}>
          Loading conversation...
        </ThemedText>
      </View>
    );
  }

  if (!conversation) {
    return (
      <View style={[styles.container, styles.loadingContainer]}>
        <AnimatedBackground />
        <Feather name="alert-circle" size={48} color={theme.textTertiary} />
        <ThemedText type="body" style={{ color: theme.textSecondary, marginTop: Spacing.md }}>
          Conversation not found
        </ThemedText>
      </View>
    );
  }

  const contactName = conversation.contactName || conversation.contactEmail || conversation.contactPhone || "Unknown Contact";
  const channelLabel = conversation.channel.charAt(0).toUpperCase() + conversation.channel.slice(1);

  return (
    <View style={styles.container}>
      <AnimatedBackground />
      <KeyboardAvoidingView
        style={styles.keyboardView}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        keyboardVerticalOffset={100}
      >
        <ScrollView
          ref={scrollViewRef}
          style={styles.scrollView}
          contentContainerStyle={[
            styles.messagesContainer,
            { paddingBottom: Spacing.xl },
          ]}
          showsVerticalScrollIndicator={false}
        >
          <View style={styles.conversationHeader}>
            <View style={styles.contactInfo}>
              <View style={[styles.avatar, { backgroundColor: `${theme.primary}20` }]}>
                <Feather name={getChannelIcon(conversation.channel)} size={24} color={theme.primary} />
              </View>
              <View style={styles.contactDetails}>
                <ThemedText type="h4">{contactName}</ThemedText>
                <View style={styles.channelBadge}>
                  <Feather name={getChannelIcon(conversation.channel)} size={12} color={theme.textSecondary} />
                  <ThemedText type="caption" style={{ color: theme.textSecondary, marginLeft: 4 }}>
                    {channelLabel}
                  </ThemedText>
                  <View style={[styles.statusDot, { 
                    backgroundColor: conversation.status === "active" ? theme.primary : 
                                     conversation.status === "resolved" ? theme.success : theme.warning 
                  }]} />
                  <ThemedText type="caption" style={{ color: theme.textSecondary, marginLeft: 4 }}>
                    {conversation.status.charAt(0).toUpperCase() + conversation.status.slice(1)}
                  </ThemedText>
                </View>
              </View>
            </View>
          </View>

          {conversation.messages?.length === 0 ? (
            <Animated.View entering={FadeIn} style={styles.emptyMessages}>
              <Feather name="message-circle" size={48} color={theme.textTertiary} />
              <ThemedText type="body" style={{ color: theme.textSecondary, marginTop: Spacing.md, textAlign: "center" }}>
                No messages yet
              </ThemedText>
              <ThemedText type="small" style={{ color: theme.textTertiary, marginTop: Spacing.xs, textAlign: "center" }}>
                Start the conversation by sending a message
              </ThemedText>
            </Animated.View>
          ) : (
            conversation.messages?.map((msg, index) => (
              <Animated.View
                key={msg.id}
                entering={FadeInDown.delay(index * 30)}
                style={[
                  styles.messageRow,
                  msg.role === "agent" ? styles.messageRowAgent : styles.messageRowUser,
                ]}
              >
                {msg.role === "agent" ? (
                  <View style={styles.agentMessage}>
                    <View style={styles.messageHeader}>
                      {msg.wasAutoGenerated ? (
                        <View style={styles.aiBadge}>
                          <Feather name="cpu" size={10} color={theme.primary} />
                          <ThemedText type="label" style={{ color: theme.primary, marginLeft: 4 }}>
                            AI
                          </ThemedText>
                        </View>
                      ) : null}
                      <ThemedText type="caption" style={{ color: theme.textTertiary }}>
                        {formatTime(msg.createdAt)}
                      </ThemedText>
                    </View>
                    <GlassCard style={styles.messageBubble}>
                      <ThemedText type="body">{msg.content}</ThemedText>
                    </GlassCard>
                  </View>
                ) : (
                  <View style={styles.userMessage}>
                    <View style={styles.messageHeader}>
                      <ThemedText type="caption" style={{ color: theme.textTertiary }}>
                        {formatTime(msg.createdAt)}
                      </ThemedText>
                    </View>
                    <View style={[styles.messageBubble, styles.userBubble]}>
                      <ThemedText type="body">{msg.content}</ThemedText>
                    </View>
                  </View>
                )}
              </Animated.View>
            ))
          )}

          {isGeneratingAI && (
            <Animated.View entering={FadeIn} style={[styles.messageRow, styles.messageRowAgent]}>
              <View style={styles.agentMessage}>
                <View style={styles.aiBadge}>
                  <ActivityIndicator size="small" color={theme.primary} />
                  <ThemedText type="label" style={{ color: theme.primary, marginLeft: 4 }}>
                    AI Thinking...
                  </ThemedText>
                </View>
              </View>
            </Animated.View>
          )}

          {suggestedResponse && (
            <Animated.View entering={FadeIn} style={[styles.messageRow, styles.messageRowAgent]}>
              <View style={styles.agentMessage}>
                <View style={styles.messageHeader}>
                  <View style={styles.aiBadge}>
                    <Feather name="cpu" size={10} color={theme.primary} />
                    <ThemedText type="label" style={{ color: theme.primary, marginLeft: 4 }}>
                      AI SUGGESTION
                    </ThemedText>
                  </View>
                </View>
                <GlassCard style={[styles.messageBubble, styles.pendingBubble]}>
                  <ThemedText type="body">{suggestedResponse}</ThemedText>
                </GlassCard>
                <View style={styles.pendingActions}>
                  <Pressable onPress={handleApprove} style={styles.approveButton}>
                    <Feather name="check" size={18} color={theme.success} />
                    <ThemedText type="small" style={{ color: theme.success, marginLeft: 4 }}>
                      Approve & Send
                    </ThemedText>
                  </Pressable>
                  <Pressable onPress={handleEdit} style={styles.rejectButton}>
                    <Feather name="edit-2" size={16} color={theme.textSecondary} />
                    <ThemedText type="small" style={{ color: theme.textSecondary, marginLeft: 4 }}>
                      Edit
                    </ThemedText>
                  </Pressable>
                </View>
              </View>
            </Animated.View>
          )}
        </ScrollView>

        <View style={[styles.inputContainer, { paddingBottom: insets.bottom + Spacing.sm }]}>
          <GlassCard noPadding style={styles.inputWrapper}>
            <View style={styles.inputRow}>
              <TextInput
                style={styles.input}
                placeholder="Type a message..."
                placeholderTextColor={theme.textTertiary}
                value={message}
                onChangeText={setMessage}
                multiline
              />
              <Pressable
                onPress={handleSend}
                disabled={!message.trim() || sendMessageMutation.isPending}
                style={[
                  styles.sendButton, 
                  { backgroundColor: message.trim() ? theme.primary : "rgba(255, 255, 255, 0.1)" }
                ]}
              >
                {sendMessageMutation.isPending ? (
                  <ActivityIndicator size="small" color={theme.text} />
                ) : (
                  <Feather name="send" size={18} color={message.trim() ? theme.text : theme.textTertiary} />
                )}
              </Pressable>
            </View>
          </GlassCard>
        </View>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  messagesContainer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.lg,
  },
  conversationHeader: {
    marginBottom: Spacing.xl,
    alignItems: "center",
  },
  contactInfo: {
    alignItems: "center",
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.sm,
  },
  contactDetails: {
    alignItems: "center",
  },
  channelBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginLeft: Spacing.sm,
  },
  emptyMessages: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Spacing["2xl"],
  },
  messageRow: {
    marginBottom: Spacing.lg,
  },
  messageRowAgent: {
    alignItems: "flex-start",
  },
  messageRowUser: {
    alignItems: "flex-end",
  },
  agentMessage: {
    maxWidth: "85%",
  },
  userMessage: {
    maxWidth: "85%",
    alignItems: "flex-end",
  },
  messageHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    gap: Spacing.sm,
  },
  aiBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${Colors.dark.primary}20`,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: BorderRadius.xs,
  },
  messageBubble: {
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
  },
  userBubble: {
    backgroundColor: Colors.dark.primary,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
  },
  pendingBubble: {
    borderWidth: 1,
    borderColor: Colors.dark.primary,
    borderStyle: "dashed",
  },
  pendingActions: {
    flexDirection: "row",
    marginTop: Spacing.sm,
    gap: Spacing.sm,
  },
  approveButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${Colors.dark.success}15`,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: `${Colors.dark.success}30`,
  },
  rejectButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  inputContainer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    backgroundColor: "rgba(16, 22, 34, 0.9)",
    borderTopWidth: 1,
    borderTopColor: Colors.dark.glassBorder,
  },
  inputWrapper: {
    borderRadius: BorderRadius.xl,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    padding: Spacing.sm,
  },
  input: {
    flex: 1,
    color: Colors.dark.text,
    fontSize: 16,
    maxHeight: 100,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
});
